r"""Export key paper figures from upstream generated tables.

This script reads CSV outputs under paper/tables (repo-relative by default) and produces:
- paper/generated/paper_numbers.json (machine-readable)
- paper/generated/paper_numbers.tex  (LaTeX macros, to be \input{}'d)

Design goals:
- Single source of truth for key reported figures.
- No hand-editing of narrative numbers once macros are wired.
- Keep output stable and reviewable (deterministic ordering).

Usage:
    python scripts/03_export_paper_numbers.py
"""

# %%
from __future__ import annotations

import csv
import datetime as dt
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any


# %%
def _read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return list(reader)


_non_alnum = re.compile(r"[^A-Za-z0-9]+")


def _camelize(s: str) -> str:
    # Turn "close_N1.2_500" into "CloseN12500" (loses punctuation deterministically).
    parts = [p for p in _non_alnum.split(s) if p]
    if not parts:
        return "X"
    return "".join(p[:1].upper() + p[1:] for p in parts)


def _macro_name(prefix: str, variable: str, distance: str) -> str:
    # Include distance explicitly to avoid collisions and keep naming predictable.
    # Example: Rho + (Closeness500) + D500
    var_part = _camelize(variable)
    dist_part = _camelize(str(distance))
    name = f"{prefix}{var_part}D{dist_part}"
    if name[:1].isdigit():
        name = f"X{name}"
    return name


# %%
def _fmt_float(value: str, decimals: int) -> str:
    return f"{float(value):.{decimals}f}"


def _fmt_int(value: str) -> str:
    return str(int(float(value)))


@dataclass(frozen=True)
class ExportPaths:
    tables_dir: Path
    out_dir: Path

    @property
    def json_path(self) -> Path:
        return self.out_dir / "paper_numbers.json"

    @property
    def tex_path(self) -> Path:
        return self.out_dir / "paper_numbers.tex"


# %%
def export_numbers(paths: ExportPaths) -> dict[str, Any]:
    neff_csv = paths.tables_dir / "neff_segments.csv"
    bootstrap_csv = paths.tables_dir / "bootstrap_ci_segments.csv"

    previous_payload: dict[str, Any] = {}
    if paths.json_path.exists():
        try:
            previous_payload = json.loads(paths.json_path.read_text(encoding="utf-8"))
        except Exception:
            previous_payload = {}

    missing_sources: list[str] = []
    carried_forward: list[str] = []
    sources: dict[str, str] = {}

    if neff_csv.exists():
        neff_rows = _read_csv_rows(neff_csv)
        sources["neff_segments_csv"] = str(neff_csv.as_posix())
    else:
        if previous_payload.get("neff_segments"):
            neff_rows = previous_payload.get("neff_segments", [])
            carried_forward.append("neff_segments")
        else:
            neff_rows = []
        missing_sources.append(str(neff_csv.as_posix()))

    if bootstrap_csv.exists():
        bootstrap_rows = _read_csv_rows(bootstrap_csv)
        sources["bootstrap_ci_segments_csv"] = str(bootstrap_csv.as_posix())
    else:
        if previous_payload.get("bootstrap_ci_segments"):
            bootstrap_rows = previous_payload.get("bootstrap_ci_segments", [])
            carried_forward.append("bootstrap_ci_segments")
        else:
            bootstrap_rows = []
        missing_sources.append(str(bootstrap_csv.as_posix()))

    payload: dict[str, Any] = {
        "generated_at": dt.datetime.now(tz=dt.UTC).isoformat(timespec="seconds"),
        "sources": sources,
        "missing_sources": missing_sources,
        "carried_forward": carried_forward,
        "neff_segments": neff_rows,
        "bootstrap_ci_segments": bootstrap_rows,
    }
    return payload


# %%
def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def write_tex(path: Path, payload: dict[str, Any]) -> None:
    out: list[str] = []
    out.append("% This file is generated by scripts/03_export_paper_numbers.py")
    out.append("% Do not edit by hand.")
    out.append(f"% Generated at (UTC): {payload['generated_at']}")
    out.append("%")
    out.append("% Macros assume the consuming document (mdpi_submisssion/main.tex) defines: \\n{}, \\nc{}, \\pct{}")
    out.append("%")
    out.append(
        "% NOTE: LaTeX control sequence names cannot contain digits, so we store values under"
    )
    out.append("%       \\csname paperNumber@<key>\\endcsname and access via \\pn{<key>}.")

    missing = payload.get("missing_sources") or []
    if missing:
        out.append("%")
        out.append("% Missing upstream sources at generation time:")
        for m in missing:
            out.append(f"% - {m}")

    carried = payload.get("carried_forward") or []
    if carried:
        out.append("%")
        out.append("% Carried forward from existing paper_numbers.json:")
        for c in carried:
            out.append(f"% - {c}")
    out.append("")

    out.append("% Lookup macro: \\pn{<key>} -> value")
    out.append(
        "\\providecommand{\\pn}[1]{"
        "\\ifcsname paperNumber@#1\\endcsname"
        "\\csname paperNumber@#1\\endcsname"
        "\\else"
        "\\textbf{[MISSING:#1]}"
        "\\fi"
        "}"
    )
    out.append("")

    # Deterministic ordering for reviewability.
    neff_rows = sorted(
        payload.get("neff_segments", []),
        key=lambda r: (r.get("variable", ""), int(float(r.get("distance", "0"))))
        if r.get("distance")
        else (r.get("variable", ""), 0),
    )

    bootstrap_rows = sorted(
        payload.get("bootstrap_ci_segments", []),
        key=lambda r: (r.get("variable", ""), int(float(r.get("distance", "0"))))
        if r.get("distance")
        else (r.get("variable", ""), 0),
    )

    out.append("% --- Effective sample size / Moran's I (segment-level) ---")
    for r in neff_rows:
        var = r.get("variable", "")
        dist = r.get("distance", "")
        if not var or not dist:
            continue

        # neff_segments.csv columns: variable,distance,k,I,N,Neff,Neff_ratio
        I = r.get("I", "")
        neff = r.get("Neff", "")
        neff_ratio = r.get("Neff_ratio", "")

        if I:
            key = _macro_name("MoranI", var, dist)
            out.append(
                f"\\expandafter\\def\\csname paperNumber@{key}\\endcsname"
                f"{{\\n{{{_fmt_float(I, 4)}}}}}"
            )
        if neff:
            key = _macro_name("Neff", var, dist)
            out.append(
                f"\\expandafter\\def\\csname paperNumber@{key}\\endcsname"
                f"{{\\nc{{{_fmt_int(neff)}}}}}"
            )
        if neff_ratio:
            # Store ratio as a percentage number (e.g., 8.7) and format with \pct{}
            key = _macro_name("NeffPct", var, dist)
            pct_val = float(neff_ratio) * 100.0
            out.append(
                f"\\expandafter\\def\\csname paperNumber@{key}\\endcsname{{\\pct{{{pct_val:.1f}}}}}"
            )

    out.append("")
    out.append("% --- Block-bootstrap Spearman (segment-level, vs pca_1) ---")
    for r in bootstrap_rows:
        var = r.get("variable", "")
        dist = r.get("distance", "")
        if not var or not dist:
            continue

        rho = r.get("rho", "")
        ci_low = r.get("ci_low", "")
        ci_high = r.get("ci_high", "")
        Neff = r.get("Neff", "")

        if rho:
            key = _macro_name("Rho", var, dist)
            out.append(
                f"\\expandafter\\def\\csname paperNumber@{key}\\endcsname"
                f"{{\\n{{{_fmt_float(rho, 3)}}}}}"
            )
        if ci_low:
            key = _macro_name("CILow", var, dist)
            out.append(
                f"\\expandafter\\def\\csname paperNumber@{key}\\endcsname"
                f"{{\\n{{{_fmt_float(ci_low, 3)}}}}}"
            )
        if ci_high:
            key = _macro_name("CIHigh", var, dist)
            out.append(
                f"\\expandafter\\def\\csname paperNumber@{key}\\endcsname"
                f"{{\\n{{{_fmt_float(ci_high, 3)}}}}}"
            )
        if ci_low and ci_high:
            key = _macro_name("CI", var, dist)
            out.append(
                f"\\expandafter\\def\\csname paperNumber@{key}\\endcsname"
                f"{{[\\n{{{_fmt_float(ci_low, 3)}}}, \\n{{{_fmt_float(ci_high, 3)}}}]}}"
            )
        if Neff:
            key = _macro_name("NeffBoot", var, dist)
            out.append(
                f"\\expandafter\\def\\csname paperNumber@{key}\\endcsname"
                f"{{\\nc{{{_fmt_int(Neff)}}}}}"
            )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out) + "\n", encoding="utf-8")


# %%
repo_root = Path(__file__).resolve().parents[1] if "__file__" in globals() else Path.cwd()
tables_dir = (repo_root / "paper/tables").resolve()
out_dir = (repo_root / "paper/generated").resolve()

paths = ExportPaths(tables_dir=tables_dir, out_dir=out_dir)
payload = export_numbers(paths)

write_json(paths.json_path, payload)
write_tex(paths.tex_path, payload)

print(f"Wrote {paths.json_path}")
print(f"Wrote {paths.tex_path}")
